title: Universal Open Textbook Initiative
description: The Universal Open Textbook Initiative (UOTI) aims to provide free, high-quality textbooks for all learners. Get started by selecting a language, learner age, and subject from the available options.
permalink: /:title/
